input_features:
    -
        name: Type
        type: category
    -
        name: Age
        type: numerical
        preprocessing:
          missing_value_strategy: fill_with_mean
    -
        name: Breed1
        type: category
    -
        name: Breed2
        type: category
    -
        name: Gender
        type: category
    -
        name: Color1
        type: category
    -
        name: Color2
        type: category
    -
        name: Color3
        type: category
    -
        name: MaturitySize
        type: category
    -
        name: FurLength
        type: category
    -
        name: Vaccinated
        type: category
    -
        name: Dewormed
        type: category
    -
        name: Sterilized
        type: category
    -
        name: Health
        type: category
    -
        name: Quantity
        type: numerical
        preprocessing:
          missing_value_strategy: fill_with_const
          fill_value: 1
    -
        name: Fee
        type: numerical
    -
        name: Description
        type: text
#    -
#        name: Photo
#        type: image
#        preprocessing:
#          height: 128
#          width: 128
#          num_channels: 3

output_features:
    -
        name: AdoptionSpeed
        type: category